# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20180720_2309'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未提交'), (1, '已提交'), (2, '迟交')], verbose_name='作业状态')),
                ('teacher_comments', models.TextField(blank=True, null=True, verbose_name='导师点评')),
                ('score', models.SmallIntegerField(default=0, verbose_name='分数')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Homework')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生作业记录',
                'verbose_name_plural': '学生作业记录',
                'db_table': '学生作业记录',
            },
        ),
    ]
