# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180721_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkrecord',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
    ]
