# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_homeworkrecord_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未提交'), (1, '待批改'), (3, '已批改'), (4, '迟交')], verbose_name='作业状态'),
        ),
    ]
